### ISSUE TITLE
Is ngSharePointFormPage ready to use

### ISSUE THREAD

**Issue by tendollartraining** [Kaldeera/ng-SharePoint#12]
Nice Module! Is ngSharePointFormPage on a build cycle? Is there any docs yet on how to use ngSharePointFormPage?
You show an animated gif of pages doing crud operations on lists- that is what I am interested in. Thank you !

**Comment by PauCodina** [comment]
ngSharePointFormPage is an angular module that can be bootstra into a sharepoint list item form page (edit/display/new) and can be used to replace standard SharePoint forms with new full featured forms:
* Angular based
* Rule based
* Free layout
* Dependent fields
* ...

We are working on a free editor to help you use this directives in a easy way.
Keep in touch for further information.
