### ISSUE TITLE
Need any help on this project?

### ISSUE THREAD

**Issue by tendollartraining** [Kaldeera/ng-SharePoint#13]
I am a sharepoint developer and angular js programmer, I am looking for an open -source project to contribute to - what do you need done?

**Comment by PauCodina** [comment]
Yes, sure. We need help!!
I do not know what kind of skills you have, neither how many time you disposes to dedicate to contribute.
What are you thinking about? Make deep code, write some documentation, make a sample app, ...
Any help will be appreciated.

**Comment by tendollartraining** [comment]
Hello Pau- I am interested in creating a sample application using ng-sharepoint and specifically using the directive <spform></spform>. I create free training videos to help developers use open-source projects https://www.udemy.com/u/markkendall/
You said you are creating an editor and I could help beta test. 
With info path forms going away, I think your product has lots of potential and I want to be an early adopter on my sites. I would like to get a demo running here https://kendallsoft-public.sharepoint.com/blog
