### ISSUE TITLE
where comes "ctx" from

### ISSUE THREAD

**Issue by S3bb1** [Kaldeera/ng-SharePoint#2]
Hi, 

i looked into your library and looks quite nice! I wanted to test it and always get a error with the "ctx" variable on https://github.com/Kaldeera/ng-SharePoint/blob/master/src/sharepoint/ng-sharepoint-formpage.js#L68

can you tell me where the variable comes frome ?

Greetings

**Comment by PauCodina** [comment]
Hi,

Actually, this file belongs to an internal system we use to replace the standard forms of SharePoint by intelligent forms ng-SharePoint.
We has entered in error and in the next commits will remove it.

**Comment by S3bb1** [comment]
Thx  @PauCodina  for the informations :) will look forward to this nice project!
