### ISSUE TITLE
wrong url when loadings scripts in subsites

### ISSUE THREAD

**Issue by mdissel** [Kaldeera/ng-SharePoint#26]
The loadscript function load the scripts from the subsite site and returns a HTTP 404 not found result

I've changed the code to, but this will break on SP 2010..
```
            loadScript: function(scriptFilename, functionName) {

                var deferred = $q.defer();

                //if (SPConfig.options.force15LayoutsDirectory) {
                    SP.SOD.registerSod(scriptFilename, '/_layouts/15/' + scriptFilename);
                //} else {
                   // SP.SOD.registerSod(scriptFilename, SP.Utilities.Utility.getLayoutsPageUrl(scriptFilename));
                //}

                EnsureScriptFunc(scriptFilename, functionName, function() {
                    deferred.resolve();
                });

                return deferred.promise;
            },
```

**Comment by PauCodina** [comment]
In SP 2010 `_layouts` directory doesn't have `15` prefix. For this reason you gets a 404 error.

`force15LayoutsDirectory` option is introduced to solve an issue on sites migrated from 2010 to 2013 that doesn't has upgraded UI. In this case, `getLayoutsPageUrl` returns an incorrect path.

The `SP.Utilities.Utility.getLayoutsPageUrl` method, returns the correct path to load the script file. It could be loaded from a subsite, it depends where the code are running, but this shouldn't be a problem.

**Comment by mdissel** [comment]
That's exactly the case. I'm using SP2013 with upgraded db from SP2010 to 2013 without upgraded UI, When I use the function from a subsite i get the url from the subsite and the url becomes /subsite/_layouts/ etc resulting in a 404.

**Comment by PauCodina** [comment]
Ok, then you must set `force15LayoutsDirectory` to true in order to solve the issue.

```javascript
angular.module('yourmoduleapp').config(['SPConfigProvider', function (SPConfigProvider) {
	SPConfigProvider.options.force15LayoutsDirectory = true;
}])
```
