### ISSUE TITLE
CultureInfo in spitem-authoringinfo.js always returns english

### ISSUE THREAD

**Issue by ViktorHofer** [Kaldeera/ng-SharePoint#31]
Hi,

the rendering of the authoring Information in spitem-authoringinfo.js always returns the english format for me. This is the code piece where the current culture is determined:
`scope.cultureInfo = (typeof __cultureInfo == 'undefined' ? Sys.CultureInfo.CurrentCulture : __cultureInfo);`

After researching a lot, it seems that SharePoint returns the wrong CurrentCulture. The object _spPageContextInfo returns the correct values:

`spPageContextInfo.currentLanguage
1031
_spPageContextInfo.currentCultureName
"de-DE"
_spPageContextInfo.currentUICultureName
"de-DE"`

Maybe there is another way of formatting those dates with the _spPageContextInfo values?

**Comment by PauCodina** [comment]
Hi Viktor,

As you say, SharePoint, by default, doesn't provide a right CultureInfo for the current user. If you want to force this, you need to modify a master-page parameter that forces to SharePoint to generate a context variable called  `__cultureInfo`. This variable contains culture settings for the user. After that, the spitem-authoringinfo will work right.

You must edit your masterpage. Locate the `<asp:ScriptManager>` server control, and modify the attribute `EnableScriptGlobalization`, setting his value to `true`. You will have something like this:

`<asp:ScriptManager runat="server" EnableScriptGlobalization="true" EnableScriptLocalization="true"  />`

You can find [here documentation about this attribute](https://msdn.microsoft.com/es-es/library/system.web.ui.scriptmanager.enablescriptglobalization(v=vs.110).aspx).
