### ISSUE TITLE
Sharepoint Add-Ins

### ISSUE THREAD

**Issue by Abrissirba** [Kaldeera/ng-SharePoint#54]
Hi

I have started to develop a SharePoint Add-In with angular and thought of trying this library. My add-in needs to get list items from the host-web so I tried getLists() from my host web but failed. Have any considerations been made around support for CORS requests to the host web in an add-in? If not, do you have any suggestion on the "correct" way to add support for this to the library. I'm happy to help out if needed.

**Comment by PauCodina** [comment]
Hi Marcus,

You have a short usage demo in the [documentation page](https://github.com/Kaldeera/ng-SharePoint/wiki) where you can learn how to instantiate a SPList object and retrieve list items.

This call returns a collection of [SPListItem](http://kaldeera.github.io/ng-SharePoint/docs/#/api/ngSharePoint.SPListItem) objects. They has methods to `remove` and `save` to the server.

<code>
taskList.getItemById(taskId).then(function(task) {
    task.Status = "Closed";
    task.save().then(function() {     
        SP.UI.Notify.addNotification("Task closed!", false);
    });
});
</code>

Also,

**Comment by Abrissirba** [comment]
Hi, my question was more about making requests for data in the Host Web when you are in an App Web. Since SharePoints Add-In architecture is so that Add-Ins are hosted on a separate domain than the Host Web you need to support CORS. This is not supported in this library from what I understand. Am I correct? Please refer to this article [https://msdn.microsoft.com/en-us/library/office/fp179927.aspx](https://msdn.microsoft.com/en-us/library/office/fp179927.aspx). The apiUrl is slightly different from what you are used to. I tried to change the getList() function to conform this pattern and it worked.

> /_api/SP.AppContextSite(@target)/web/title?@target='" + hostweburl + "'"
