### ISSUE TITLE
ReferenceError: SPListItem is not defined

### ISSUE THREAD

**Issue by BmanthaBernard** [Kaldeera/ng-SharePoint#60]
When attempting to create a new list item I am receiving a not defined on the contructor.  I am able to retrieve items from the list without issue.

	$scope.AddToList = function (notInItem){
		 SharePoint.getWeb('/teams/ConsumerOperations/process').then(function(web) {

			
			web.getList('PMO Projects Tracking').then(function(list) {
		
				var item = new SPListItem(list); // <== throws error
				
				item.Title = notInItem['Project Name'];
				item.PMO_x0020_Project_x0020_Number = notInItem['Project ID'];
				item.PMO_x0020_Project_x0020_Portfoli = notInItem['Portfolio'];
				item.Project_x0020_Description = notInItem['Project Description']
				item.PMO_x0020_Project_x0020_Executiv = notInItem['Executive Sponsor'];
				item.PMO_x0020_Project_x0020_Business = notInItem['Business Owner'];
				item.PMO_x0020_Project_x0020_Manager = notInItem['Project Manager'];
				item.PMO_x0020_Project_x0020_Status = notInItem['Project Status'];
				item.PMO_x0020_Project_x0020_Start_x0 = notInItem['Start Date'];
				item.PMO_x0020_Project_x0020_End_x002 = notInItem['End Date'];
				

		 
				item.save().then(function() {
				   console.log('item saved');
				});
			});	
		});	
	};

**Comment by PauCodina** [comment]
Hi Bernard,

Have you inject the SPListItem service into your scope?
Which kind of error throws?

**Comment by BmanthaBernard** [comment]
That was It.  Missed that is was a separate service.  makes sense now that
I look at the factory.

Thanx for the quick response.

P.S.  Love using ng-sharepoint
